name: Run tests

 

on:

  workflow_dispatch:
  push:
   branches: [main]
  pull_request:
    branches: [main]

  

jobs:

  test:

    name: Test

    runs-on: ubuntu-22.04

 

    container:

      image: node:20

 

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

        with:

          node-version: '20'

      - uses: browser-actions/setup-chrome@v1

        with:

          chrome-version: 120

          install-dependencies: true

      - name: Build backend with mave
        run: |
            cd backend/calculatorbe/
            mvn clean spring-boot:run & 
            echo "Waiting 5 seconds for the server to start"
            sleep 5
            attempt_counter=0
            max_attempts=5
            until $(curl --output /dev/null --silent --head --fail http://localhost:8081/add?num1=5&num2=7); do
              if [ ${attempt_counter} -eq ${max_attempts} ];then
                echo "Max attempts reached"
                exit 1
              fi
            
              printf '.'
              attempt_counter=$(($attempt_counter+1))
              sleep 5
             done
             echo "sever ready for testing"
            
      - name: Run frotend test
        run : |
            cd ../../frontend/
            npm install
            cd src/
            python3 -m http.server 8000 &
            sleep 20 &&
            curl http://localhost:8000
            cd tests
            ../node_modules/.bin/mocha *.js
       
      - uses: actions/upload-artifact@v4

        if: always()

        with:

          name: screenshots

          path: screenshots/
