name: Full Test
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs: 
  build:
    runs-on: ubuntu-latest
    container : 
      image : node:20
    steps:
      - uses : actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true
      - name : Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up node 20 
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name : Build with Maven
        run: |
          cd backend/calculatorbe
           mvn clean spring-boot:run & 
           echo "waiting 5 seconds for the server to start"
           sleep 5 
           attempt_counter=0
           max_attempts=5
           until $(curl --output /dev/null --silent --head --fail http://localhost:8080/add?num1=5&num2=7); do
              if [ ${attempt_counter} -eq ${max_attempts} ];then
                echo "Max attempts reached"
                exit 1
              fi
          
              printf '.'
              attempt_counter=$(($attempt_counter+1))
              sleep 5
           done
           echo "sever ready for testing"

      - name : Run backend tests
        run: |
          npm install -g newman
          newman -v
          newman run backend/calculatorbe/src/test/integration/calculator.postman_collection.json
          echo "Backend tests finished!"

      - name : Run frontend tests
        run: |
            cd frontend/
            npm install
            cd src/
            python3 -m http.server 8000 &
            sleep 20 &&
            curl http://localhost:8000
            cd ../tests
            ../node_modules/.bin/mocha *.js 
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshots/
        

           
          
